
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.mycompany.property;
import java.util.Dictionary;
import java.util.Hashtable;
import javax.swing.DefaultListModel;



/**
 *
 * @author ahmad
 */
public class Home extends javax.swing.JFrame {
CRMFacade Propertiy = CRMFacade.getInstance();
DefaultListModel listModel = new DefaultListModel();
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
      this.AddLead.setVisible(false);
      this.CompoundInfo.setVisible(false);
      
      
        for(AddLead i: this.Propertiy.getPropertiyAddLead())
        {
            listModel.addElement(i.getName());
        }
        this.LeadList.setModel(listModel);

    }
       public void updateList()
    {
        listModel = new DefaultListModel();
        for(AddLead i: this.Propertiy.getPropertiyAddLead())
        {
            listModel.addElement(i.getName());
        }
        this.LeadList.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel2 = new javax.swing.JPanel();
        AddLead = new javax.swing.JInternalFrame();
        VillaInfo = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        ACInput = new javax.swing.JTextField();
        CamsInput = new javax.swing.JTextField();
        WatchmenInput = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        PhoneInput = new javax.swing.JTextField();
        interInput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lastInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TypeInput = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        NameInput = new javax.swing.JTextField();
        CompoundInfo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        SecurityInput = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        PoolInput = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        GymInput = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LeadList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        LeadDetails = new javax.swing.JTextPane();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );

        AddLead.setVisible(true);

        jLabel23.setText("AC_Type");

        jLabel24.setText("Cameras");

        ACInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACInputActionPerformed(evt);
            }
        });

        CamsInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CamsInputActionPerformed(evt);
            }
        });

        WatchmenInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WatchmenInputActionPerformed(evt);
            }
        });

        jLabel25.setText("WatchMen");

        javax.swing.GroupLayout VillaInfoLayout = new javax.swing.GroupLayout(VillaInfo);
        VillaInfo.setLayout(VillaInfoLayout);
        VillaInfoLayout.setHorizontalGroup(
            VillaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VillaInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(VillaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(41, 41, 41)
                .addGroup(VillaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CamsInput, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ACInput, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WatchmenInput, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        VillaInfoLayout.setVerticalGroup(
            VillaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VillaInfoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(VillaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WatchmenInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(VillaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(ACInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(VillaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(CamsInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        PhoneInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneInputActionPerformed(evt);
            }
        });

        interInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interInputActionPerformed(evt);
            }
        });

        jLabel1.setText("Type");

        jLabel2.setText("Name");

        jLabel3.setText("Phone");

        lastInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastInputActionPerformed(evt);
            }
        });

        jLabel4.setText("Interseted");

        TypeInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Villa", "Compound" }));
        TypeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeInputActionPerformed(evt);
            }
        });

        jLabel5.setText("Last");

        NameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameInputActionPerformed(evt);
            }
        });

        jLabel12.setText("Security_guard");

        SecurityInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecurityInputActionPerformed(evt);
            }
        });

        jLabel11.setText("Pool");

        PoolInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PoolInputActionPerformed(evt);
            }
        });

        jLabel13.setText("Gym");

        GymInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GymInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CompoundInfoLayout = new javax.swing.GroupLayout(CompoundInfo);
        CompoundInfo.setLayout(CompoundInfoLayout);
        CompoundInfoLayout.setHorizontalGroup(
            CompoundInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CompoundInfoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(CompoundInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(CompoundInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PoolInput, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecurityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GymInput, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        CompoundInfoLayout.setVerticalGroup(
            CompoundInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CompoundInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CompoundInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(SecurityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CompoundInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(PoolInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(CompoundInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(GymInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jButton1.setText("Add Lead");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddLeadLayout = new javax.swing.GroupLayout(AddLead.getContentPane());
        AddLead.getContentPane().setLayout(AddLeadLayout);
        AddLeadLayout.setHorizontalGroup(
            AddLeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLeadLayout.createSequentialGroup()
                .addGroup(AddLeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddLeadLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(AddLeadLayout.createSequentialGroup()
                        .addGroup(AddLeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddLeadLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(AddLeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGroup(AddLeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AddLeadLayout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(TypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(AddLeadLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addGroup(AddLeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(interInput, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lastInput, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PhoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(AddLeadLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(VillaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddLeadLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(CompoundInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 71, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AddLeadLayout.setVerticalGroup(
            AddLeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLeadLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(AddLeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(AddLeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddLeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PhoneInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddLeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddLeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lastInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VillaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(CompoundInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        LeadList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LeadListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(LeadList);

        jScrollPane2.setViewportView(LeadDetails);

        jLabel15.setText("Details");

        jLabel16.setText("Leads");

        jButton2.setText("Add Lead");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TableLayout = new javax.swing.GroupLayout(Table);
        Table.setLayout(TableLayout);
        TableLayout.setHorizontalGroup(
            TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TableLayout.createSequentialGroup()
                .addGroup(TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TableLayout.createSequentialGroup()
                        .addGroup(TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TableLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2)))
                            .addGroup(TableLayout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jLabel15))
                            .addGroup(TableLayout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jLabel16)))
                        .addGap(0, 145, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TableLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        TableLayout.setVerticalGroup(
            TableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TableLayout.createSequentialGroup()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(875, 875, 875)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(355, Short.MAX_VALUE)
                .addComponent(Table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(AddLead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1372, 1372, 1372))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(AddLead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(Table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.Table.setVisible(false);
        this.AddLead.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String type = TypeInput.getSelectedItem().toString();
        String name = NameInput.getText();
        String phone = PhoneInput.getText();
        String intersted = interInput.getText();
        String Last =lastInput.getText();
        Dictionary info = new Hashtable();
        if(TypeInput.getSelectedItem().equals("Compound"))
        {
            info.put("Pool",PoolInput.getText());
            info.put("Security_guard",SecurityInput.getText());
            info.put("Gym",GymInput.getText());
        }
        else if(TypeInput.getSelectedItem().equals("Villa"))
        {
            info.put("Watchman",WatchmenInput.getText());
            info.put("Ac_Type",ACInput.getText());
            info.put("Cameras",CamsInput.getText());
        }
        this.Propertiy.addAddLead(name, type, phone, Last, intersted, info);
        updateList();
        this.AddLead.setVisible(false);
        this.Table.setVisible(true);
        NameInput.setText("");
        PoolInput.setText("");
        SecurityInput.setText("");
        GymInput.setText("");
        WatchmenInput.setText("");
        ACInput.setText("");
        CamsInput.setText("");
        PhoneInput.setText("");
        interInput.setText("");
        lastInput.setText("");
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GymInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GymInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GymInputActionPerformed

    private void PoolInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PoolInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PoolInputActionPerformed

    private void SecurityInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecurityInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecurityInputActionPerformed

    private void NameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameInputActionPerformed

    private void TypeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeInputActionPerformed
        System.out.println(TypeInput.getSelectedItem());
        if(TypeInput.getSelectedItem().equals("Villa"))
        {
            this.CompoundInfo.setVisible(false);
            this.VillaInfo.setVisible(true);
        }
        else if(TypeInput.getSelectedItem().equals("Compound"))
        {
            this.CompoundInfo.setVisible(true);
            this.VillaInfo.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeInputActionPerformed

    private void lastInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastInputActionPerformed

    private void interInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interInputActionPerformed

    private void PhoneInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneInputActionPerformed

    private void WatchmenInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WatchmenInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WatchmenInputActionPerformed

    private void CamsInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CamsInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CamsInputActionPerformed

    private void ACInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ACInputActionPerformed

    private void LeadListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeadListMouseClicked
int i = this.LeadList.getSelectedIndex();
        AddLead it = this.Propertiy.getAddLead(i);
        if(it.getType().equals("Villa"))
       {
           this.LeadDetails.setText("Name: " +it.getName() 
                    + "\nType: "+it.getType()+"\nPhone:"+it.getPhone()+"\nInterested:"+it.getInter()+"\nLast:"+it.getLast()
            +"\nAc_Type:"+((Villa)it).getAC_Type()+"\nCameras:"+((Villa)it).getCameras()+ "\nWatchman: " + ((Villa)it).getWatchman());
       }
        else{
             this.LeadDetails.setText("Name: " +it.getName() + "\nType: "+it.getType()+"\nPhone:"+it.getPhone()+"\nInterested:"+it.getInter()+"\nLast:"+it.getLast()
            +"\nSecurity_guard:"+((Compound)it).getSecurity_guard()+"\npool:"+((Compound)it).getPool()+"\nGym:"+((Compound)it).getGym());
        }  
    }//GEN-LAST:event_LeadListMouseClicked
  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ACInput;
    private javax.swing.JInternalFrame AddLead;
    private javax.swing.JTextField CamsInput;
    private javax.swing.JPanel CompoundInfo;
    private javax.swing.JTextField GymInput;
    private javax.swing.JTextPane LeadDetails;
    private javax.swing.JList<String> LeadList;
    private javax.swing.JTextField NameInput;
    private javax.swing.JTextField PhoneInput;
    private javax.swing.JTextField PoolInput;
    private javax.swing.JTextField SecurityInput;
    private javax.swing.JPanel Table;
    private javax.swing.JComboBox<String> TypeInput;
    private javax.swing.JPanel VillaInfo;
    private javax.swing.JTextField WatchmenInput;
    private javax.swing.JTextField interInput;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lastInput;
    // End of variables declaration//GEN-END:variables
}
